stages:
- test

cache:
  key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
  paths:
  - _vendor-cache/

before_script:
- mkdir -p _vendor-cache /var/go/ours
- ln -s "$(pwd -P)/_vendor-cache" /var/go/theirs
- export GOPATH=/var/go/theirs:/var/go/ours
- export GODIR=/var/go/ours/src/blitznote.com/src/go.runtime
- mkdir -p "$(dirname "$GODIR")"
- ln -sfv "$(pwd -P)" "$GODIR"
- cd "$GODIR"
- go get -d
- tree /var/go -d -L 4 || true

vet:
  stage: test
  script:
  - diff <(echo -n) <(gofmt -s -d .)
  - go vet ./...

lint:
  stage: test
  script:
  - /var/go/provided/bin/ineffassign .
  - /var/go/provided/bin/golint ./...

unittests:
  stage: test
  script:
  - go test -v ./...
