tags: ['golang']
timeout: 60s

steps:
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'gofmt'
  entrypoint: 'bash'
  args: ['-c', 'diff <(echo -n) <(gofmt -s -d $(find . -type f -name "*.go" -not -path "./_*"))']

- &build_go
  name: 'gcr.io/cloud-builders/go:debian'
  id: 'build Linux amd64, Go current'
  env: ['GOARCH=amd64', 'GOOS=linux']
  args: ['build', '.', 'errors']
- <<: *build_go
  id: 'build Windows amd64, Go current'
  env: ['GOARCH=amd64', 'GOOS=windows']

- name: 'gcr.io/cloud-builders/go:debian'
  id: 'test'
  args: ['test', '-v', './...']

- name: 'gcr.io/blitznote/golang/ineffassign'
  id: 'ineffassign'
  waitFor: ['test']
  args: ['.']
- name: 'gcr.io/blitznote/golang/golint'
  id: 'lint'
  waitFor: ['test']
